"""Add email to User model

Revision ID: 4c7c652166d7
Revises: adad9bbf42ea
Create Date: 2025-01-21 20:59:10.381681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7c652166d7'
down_revision = 'adad9bbf42ea'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add the email column
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
