"""Add user_id to Student model

Revision ID: adad9bbf42ea
Revises: 
Create Date: 2025-01-21 20:28:42.035875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adad9bbf42ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_student_user',  # Explicitly name the foreign key
            'user',
            ['user_id'],  # Local column
            ['id']         # Referenced column
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
